### ISSUE TITLE
Local file update

### ISSUE THREAD

**Issue by damre** [alex-spataru/QSimpleUpdater#10]
Hi! thanks for the great project!
I was wondering if it was possible to make the updater use a local updates.json that has a reference to a zip file written on the disk instead of downloading it from an online source.

this is the situation:
```
-> QApplication Folder
      -> UpdateFolder
              -> updates.json
              -> update.zip
      -> app files
```

Is it possible to use the QSimpleUpdater in this situation? 

thank you so much

**Comment by alex-spataru** [comment]
In order to do that, it would be needed to modify the [Updater](https://github.com/alex-spataru/QSimpleUpdater/blob/master/src/Updater.h) class. The only thing that should be changed is how QSimpleUpdater obtains the *updates.json* file. You can check [this function](https://github.com/alex-spataru/QSimpleUpdater/blob/master/src/Updater.cpp#L350) to see what you can do when you already have the QByteArray data of the JSON file.

Then, in the *updates.json* file, you could change the `open-url` variable to `file://<location of local file>`.
