### ISSUE TITLE
Cannot download SourceForge files

### ISSUE THREAD

**Issue by wangwenx190** [alex-spataru/QSimpleUpdater#13]
I think it's redirection's problem. Maybe QNetworkReply cannot handle redirection properly.

**Comment by wangwenx190** [comment]
@alex-spataru Hi, I'm wondering why this issue was closed. Is it confirmed and solved?

**Comment by alex-spataru** [comment]
@wangwenx190 Hi, the redirection should have been fixed in a previous issue. Unfortunately, I did not have time to maintain this project & keep up with issues/PR/etc. Thus, I closed old issues without comments to make some order & focus on current issues/bugs. 

Can you please check if this issue still persists in your test scenario?  If so, please notify me so that I can re-open this issue and see what can be done. Happy new year!

**Comment by wangwenx190** [comment]
@alex-spataru Happy new year!

Actually I'm using QNetworkXXX to achieve my own updater, and I encounter with this issue as well. Qt Network's redirection works well on most websites, but it doesn't work with SoureForge. I'm not able to download any file from SF either. It seems it's not a bug of your repo, it's something wrong with Qt Network itself. I didn't test Qt 5.15, but I'm sure Qt 5.14 still has this issue.

I will not re-open this issue because I think it's not related to your code.
