### ISSUE TITLE
Could I update the Qt dll by this library?

### ISSUE THREAD

**Issue by stereomatchingkiss** [alex-spataru/QSimpleUpdater#3]
Thanks for sharing this cool library.

Operating is windows, Qt version is Qt5.6

The case is, I shift my app in a folder with Qt5 dll
I believe QSimpleUpdater will need dll of Qt5 to run
Could QSimpleUpdater able to update(replace) the dll under this case?

Edit : 

The solution I am considering are

1 : use QSimpleUpdater to download all of the dll + exe(updater) from the url
2 : start the updater
3 : close the running application(myApp)
4 : updater copy the dll into the folder of myApp
5 : start myApp
6 : myApp detect the folder of updater
7 : delete the folder of updater

**Comment by alex-spataru** [comment]
Your solution should work. By default, the QSimpleUpdater will save its downloaded files on a temporary directory (specified by each operating system). However, the program/script that you use to copy the files should not have a Qt dependency (for example, you can use [NSIS](http://nsis.sf.net) to create an installer that updates your DLLs). 

In my opinion, steps 6 and 7 are not really necessary, since the OS will deal with the temporary files by itself.

As a final note, you can build QSimpleUpdater as a DLL or integrate it with your application using the project includes (check [tutorial.pro](https://github.com/alex-spataru/QSimpleUpdater/blob/master/tutorial/tutorial.pro#L18) for more info).

**Comment by stereomatchingkiss** [comment]
Thanks, I will let you know if it works.

**Comment by alex-spataru** [comment]
Perfect, let me know if you need any help 👍
